version: "3"
nginx:
  container_name: nginx
  build: ./nginx
  links:
    - app:app
  ports:
    - "80:80"

app:
  container_name: app
  build:
    context: .
    dockerfile: Dockerfile
   - mysql:mysql
  ports:
    - "3000"
  restart: always

mysql:
  container_name: mysql
  image: mysql:5.5
  restart: always
  ports:
    - "3306"
  volumes:
    - mysql:/home/data/db
  environment:

redis:
  container_name: redis
  image: redis:alpine
  ports:
    - "6379"
  volumes:
    - redis:/home/data/redis
  restart: always
